### DISCUSSION TITLE
Adding floating URL bar

### DISCUSSION THREAD

**Discussion by djenttleman** [yiiyahui/Neptune-Firefox#60] [Ideas]
Hi.
I would suggest to add an option for floating URL bar.
Tried by myself but I couldn't get it work.

Here's the code:
`/* 
  create a file named userChrome.css within a directory named chrome
  in the .mozilla/firefox/$profile-id.$your-profile-name or wherever
  your firefox stores your profile.
*/

/* "floating" urlbar */
#urlbar[breakout][breakout-extend]{
  top: 200px !important;
  left: 50% !important;
  max-width: 900px !important;
  width: 90% !important;
  transform: translateX(-50%);
  padding: 7px !important;
  font-size: 18px !important;
}

/* remove zoom indicator */
#urlbar[breakout][breakout-extend] #urlbar-zoom-button {
  display: none !important;
}

/* remove search engine buttons in last line */
#urlbar[breakout][breakout-extend] .search-one-offs{
  display: none !important;
}

/* remove useless first line */
#urlbar[breakout][breakout-extend] .urlbarView-row:first-of-type {
  display: none !important;
}

/* remove "Firefox Suggest" and "Google Suggestions" labels */
#urlbar[breakout][breakout-extend] .urlbarView-row[label]::before {
  display: none !important;
}
#urlbar[breakout][breakout-extend] .urlbarView-row[label] {
  margin-block-start: 0 !important;
}
`

Any ideas?

**Comment by yiiyahui** [comment]
Personally, I’m not a fan of the floating address bar, and it doesn't suit a horizontal layout. The next update will modularize the code to facilitate the addition of extra features, such as native windows title buttons.
This is a simple example that only works in vertical layout.

```css
/* floating urlbar */
@media -moz-pref("sidebar.verticalTabs") {
	#urlbar {
		transition: transform 300ms ease-in-out !important;

		&[open] > #urlbar-background {
			box-shadow: var(--neptune-menu-shadow) !important;
		}

		&[breakout-extend] {
			background-color: var(--toolbar-bgcolor) !important;
			transform: translateY(15vh) scale(1.25);
		}
	}
}
```
