### ISSUE TITLE
New tab, extensions and menu buttons are spread out weirdly

### ISSUE THREAD

**Issue by twigtarsier** [yiiyahui/Neptune-Firefox#17]
I use Linux Mint cinnamon and as the title describes the buttons are really spread out and overlap the tabs for some reason. 
![image](https://github.com/user-attachments/assets/0bda213c-ed12-4f91-b66b-ef419b998656)
I really like this firefox css and I hope you can find a fix!

**Comment by yiiyahui** [comment]
Search for 

```css
#tabs-newtab-button,
#TabsToolbar #new-tab-button {
	position: absolute;
	..................
}
```

TO


```css
#tabs-newtab-button,
#TabsToolbar #new-tab-button {
	position: fixed;
	..................
}
```

 I don't have Linux to test it, you try it.
