### ISSUE TITLE
 close tab icon to the left like in recent safari

### ISSUE THREAD

**Issue by alien-infj** [yiiyahui/Neptune-Firefox#28]
Thank you for this elegant theme & I appreciate your work.

<img width="995" alt="Screenshot 2024-11-27 at 5 14 58 PM" src="https://github.com/user-attachments/assets/c2990bd4-4ee8-4f96-8f6d-442c1cc4a7ca">

How can I make close tab icon appear in the left of tabs like in recent safari & other icons(speaker) to the right?

<img width="1920" alt="Screenshot 2024-11-27 at 5 16 08 PM" src="https://github.com/user-attachments/assets/0dbc3f39-ea30-4d8c-ae54-a0374bc40704">

I also would like to disable search box that appear in the middle of the wallpaper in new private browsing tab.

Thank You

**Comment by yiiyahui** [comment]
1: If the close button and the icons on the left are swapped, unless the close button is kept visible all the time, there will be a blank space. At the same time, the icons on the right look quite strange and a bit ugly, like this:

![2](https://github.com/user-attachments/assets/0686fe39-5556-4532-b306-6cb9028a5da6)

![3](https://github.com/user-attachments/assets/a91ea489-aefe-48a8-a1cb-657accb7f0e7)

However, it is possible to have them all on the left, where the close button becomes visible on hover and the favicon is hidden. but the speaker icon would also be completely gone.

So the actual issue is the position of the speaker icon. In fact, the speaker icon in safari is located inside the urlbar.

This should be a more reasonable solution if you don't mind losing the speaker icon. Here is the code:

```css
tab:hover .tab-icon-stack:not([pinned]) {
	visibility: collapse;
}

.tab-close-button {
	order: -1;
	margin-inline-end: calc(var(--tab-icon-end-margin) + 4px) !important;
	border-radius: 2px !important;
	visibility: collapse;

	......
	......
}
```

![1](https://github.com/user-attachments/assets/1a8e41fc-0b4f-4396-9f7e-690ba62254fa)


2: To remove the search bar, you can edit userContent.css.

```css
@-moz-document url("about:privatebrowsing") {
	.search-inner-wrapper {
		height: 52px !important;
		padding: 0 !important;
		display: none !important;
	}

	......
	......
}
```
