### ISSUE TITLE
Big Window Decorations on Linux

### ISSUE THREAD

**Issue by rwxOsu** [yiiyahui/Neptune-Firefox#3]
This is peak firefox css design, the best I have used so far. Unfortunately, the window decorations on the left side are extremely large, much larger than probably intended. Reason for that is probably because I'm using Linux

System: Arch Linux with KDE Plasma with newest Firefox version

Screenshot:

![Screenshot_20240725_125227](https://github.com/user-attachments/assets/b995a488-90a9-4834-9a5e-0aa4c826b335)

I temporarily fixed it by adding this:

```
#titlebar .titlebar-buttonbox-container .titlebar-button {
width: 16px !important;
height: 16px !important;
padding: 0 !important;
margin-right: 4px !important; /* Space between buttons */
}

/* Remove margin from the last button */
#titlebar .titlebar-buttonbox-container .titlebar-button:last-child {
margin-right: 0 !important;
}

#titlebar .titlebar-buttonbox-container .titlebar-button .toolbarbutton-icon {
width: 12px !important; /* Adjust the icon width as needed */
height: 12px !important; /* Adjust the icon height as needed */
}
```

**Comment by yiiyahui** [comment]
I tried to fix them on Fedora KDE, and it seems to be fixed now.

![Screenshot 8](https://github.com/user-attachments/assets/12d51f4a-4c33-4097-b360-259c6848c15e)

```css
@media (-moz-platform: linux) {
	:root[tabsintitlebar][inFullscreen] .titlebar-buttonbox-container {
		display: none !important;
	}
	......
	
	.titlebar-button {
		appearance: none !important;
		padding-inline: 10px !important;
		height 12px;
		width: 12px;
	}
	
	.titlebar-close {
	......
```
