### ISSUE TITLE
this is not an issue , just a request

### ISSUE THREAD

**Issue by gauravrocks009** [yiiyahui/Neptune-Firefox#48]
firefox recently added translucent popup menus in the edge channel , can you please please integrate it  into neptune ?????

to enable the translucent menus , go to about:config and search for mica and enable everything. 

![Image](https://github.com/user-attachments/assets/61d43207-0e44-4acd-b1b1-cfdb78f87577)

**Comment by yiiyahui** [comment]
I'm glad to see this effect! my Windows 11 virtual machine is broken, so I can't test it. Is it currently applied only to the right click context menu, or does it also affect all popup menus, such as the download panel or the functionality menu in the url bar? Can you provide a screenshot?

**Comment by yiiyahui** [comment]
Okay, you can try to modify it; I can't test it right now. However, the navigation bar cannot be modified at the moment because the extension does not support it. If the extension is disabled, it displays normally, but some colors may appear incorrect.

----

![Image](https://github.com/user-attachments/assets/b4adb19b-ed54-4ce7-a441-99c92471d6ed)

```css
@media not (-moz-platform: macos) and @media not (-moz-windows-mica-popups) {
	menupopup {
		--panel-background: var(--menupopup-background-color) !important;
		--content-select-background-image: none !important;
		......
		......
```

or

```css
@media not (-moz-platform: macos) {
	menupopup {
		--panel-background: var(--menupopup-background-color) !important;
		--content-select-background-image: none !important;

		@media (-moz-windows-mica-popups) {
			appearance: auto !important;
			-moz-default-appearance: menupopup !important;
		}
		......
		......
```

**Comment by gauravrocks009** [comment]
not wokring , i replced the things you told me but i think i made a mistake can you send me an updated userchrome.css file instead , sorry i am not a developer , sorry 

![Image](https://github.com/user-attachments/assets/07949233-1c60-401a-a115-3dfc70a45ec4)

![Image](https://github.com/user-attachments/assets/9a21d3ae-206a-46bb-a20e-13ceae0cdf50)

**Comment by yiiyahui** [comment]
Just change
`@media not (-moz-platform: macos)`
to
`@media not (-moz-platform: macos) and @media not (-moz-windows-mica-popups)`

**Comment by gauravrocks009** [comment]
still getting the wierd outline around the popup 

![Image](https://github.com/user-attachments/assets/10d4a809-ac71-4f58-b7c1-1be2828489db)
![Image](https://github.com/user-attachments/assets/fe9f1ac2-fd53-42e8-bedd-7fbc5c8b273e)

**Comment by yiiyahui** [comment]
Try the second method, just add

```css
@media not (-moz-platform: macos) {
	menupopup {
		--panel-background: var(--menupopup-background-color) !important;
		--content-select-background-image: none !important;

/* Just add these three lines. */
		@media (-moz-windows-mica-popups) {  
			appearance: auto !important;
			-moz-default-appearance: menupopup !important;
		}
```

**Comment by gauravrocks009** [comment]
still getting the outline , please just send the css file or update it directly in a new version

**Comment by yiiyahui** [comment]
Hi, sorry for the delay in replying. Here are the fix contents for enabling the Mica menu. It's more complicated than I expected. You can copy and replace them.

----
**This is the lines to be replaced.**
https://github.com/yiiyahui/Neptune-Firefox/blob/f123af05e808668107edd272ce3fc747e022fe7b/chrome/userChrome.css#L1382-L1545

----
**This is the new code.**

```css
menupopup, panel {
	--panel-color: MenuText !important;
	--panel-border-color: var(--neptune-toolbar-border-color) !important;
	--panel-separator-color: var(--neptune-popover-separator-color) !important;
	--panel-padding-block: var(--panel-subview-body-padding-block) !important;
}

panel {
	--panel-border-radius: var(--arrowpanel-border-radius) !important;
	--panel-shadow-margin: 22px !important;
	--panel-shadow: var(--neptune-panel-shadow), 0 3px var(--panel-shadow-margin) var(--neptune-panel-shadow-color) !important;
	--arrowpanel-header-back-icon-padding: var(--space-xsmall) !important;
	--arrowpanel-header-back-icon-full-width: calc(12px + 2 * var(--arrowpanel-header-back-icon-padding)) !important;
	--arrowpanel-header-min-height: calc(var(--arrowpanel-header-back-icon-full-width) + 2 * var(--panel-separator-margin-vertical)) !important;

	:root[lwtheme] & {
		color-scheme: light dark !important;
	}

	select:where(:not([size], [multiple])) {
		margin: 0 !important;
	}

	menulist {
		padding-block: 2px !important;
	}

	toolbarseparator {
		margin-inline: calc(var(--arrowpanel-menuitem-margin-inline) + var(--arrowpanel-menuitem-padding-inline)) !important;
	}

	&[type="autocomplete-richlistbox"] {
		--panel-background: var(--arrowpanel-background) !important;

		> .autocomplete-richlistbox {
			background-color: var(--neptune-menu-background) !important;

			> .autocomplete-richlistitem {
				&:not([disabled="true"]):not([selected]):hover {
					background-color: var(--color-accent-primary-hover) !important;
					color: var(--button-text-color-primary) !important;
				}

				&[selected] {
					background-color: var(--color-accent-primary-active) !important;
					color: var(--button-text-color-primary) !important;
				}

				> .ac-type-icon {
					min-height: 12px !important;
					min-width: 12px !important;
				}

				> .ac-title {
					margin-inline: auto !important;
				}
			}
		}

		> menuseparator::before {
			display: none !important;
		}
	}

	.toolbarbutton-badge {
		background-color: var(--icon-color-warning) !important;
		line-height: 14px !important;
		border-radius: 50% !important;
	}
}

panelview .toolbarbutton-1,
toolbarbutton.subviewbutton:not(.all-tabs-secondary-button, .subviewbutton-back),
.widget-overflow-list .toolbarbutton-1,
.toolbaritem-combined-buttons:is(:not([cui-areatype="toolbar"]), [overflowedItem=true]) > toolbarbutton {

	&:not([disabled]):hover {
		background-color: var(--color-accent-primary-hover) !important;
		color: var(--button-text-color-primary) !important;

		&:active {
			background-color: var(--color-accent-primary-active) !important;
		}
	}
}

@media not (-moz-platform: macos) {
	menupopup {
		--content-select-background-image: none !important;

		@media not (-moz-windows-mica-popups) {
			--panel-background: var(--menupopup-background-color) !important;
			--panel-shadow-margin: 22px !important;
			--panel-shadow: var(--neptune-panel-shadow), 0 3px var(--panel-shadow-margin) var(--neptune-panel-shadow-color) !important;
		}

		> menu,
		> menuitem {
			padding-block: 2px !important;
			padding-inline-start: var(--arrowpanel-menuitem-padding-inline) !important;

			> .menu-right {
				margin-inline-end: var(--arrowpanel-menuitem-padding-inline) !important;
			}

			menupopup[needsgutter] &:not([checked="true"], [icon], .menu-iconic, .menuitem-iconic) {
				padding-inline-start: var(--space-xlarge) !important;
			}

			&:where([_moz-menuactive]:not([disabled="true"])) {
				background-color: var(--color-accent-primary-hover) !important;
				color: var(--button-text-color-primary) !important;
			}

			&:where([_moz-menuactive="true"][disabled="true"]) {
				background: none !important;
			}
		}

		> menuitem[checked="true"] {
			padding-inline-start: 0 !important;

			:is(#backForwardMenu, #nav-bar-customization-target) & {
				padding-inline-start: var(--space-medium) !important;
			}

			> .menu-iconic-left {
				margin-inline-end: var(--space-xsmall) !important;
			}
		}

		> #context-navigation {
			 > menuitem:where([_moz-menuactive]:not([disabled="true"])) {
				background: none !important;
				color: var(--color-accent-primary-hover) !important;
			}

			> .menuitem-iconic > .menu-iconic-left > .menu-iconic-icon {
				padding-block: var(--space-xsmall) !important;
			}
		}

		> menuseparator {
			padding: var(--panel-separator-margin) !important;
		}

		#ContentSelectDropdown > & > .ContentSelectDropdown-item-0 {
			font-size: 1rem !important;

			&:not([_moz-menuactive="true"]) {
				background-color: var(--theme-menupopup-background) !important;
				color: inherit !important;
			}
		}

		#ContentSelectDropdown > & > :is(menucaption, menuitem) > .menu-iconic-text {
			padding-block: 1px !important;
		}
	}

	@media (-moz-windows-mica-popups) {
		.toolbar-menupopup {
			--panel-shadow-margin: 22px !important;
			--panel-shadow: var(--neptune-panel-shadow), 0 3px var(--panel-shadow-margin) var(--neptune-panel-shadow-color) !important;
		}
	}
}
```
