### ISSUE TITLE
Misplaced newtab button when only single tab/no tab is open

### ISSUE THREAD

**Issue by alien-infj** [yiiyahui/Neptune-Firefox#56]
Please provide me a fix for the misplaced newtab button while only one tab/no tab is open.
<img width="1918" alt="Image" src="https://github.com/user-attachments/assets/1fdf4d5f-e91c-4de6-9f82-60ca5554c4d7" />

It's fine for 2 or more tabs

<img width="1918" alt="Image" src="https://github.com/user-attachments/assets/b9ccb2bd-0394-4ce9-ad0e-0eeb4bd408f1" />

Thank You

**Comment by yiiyahui** [comment]
I cannot reproduce this issue; the default setup already ensures that the button is vertically centered. from the image, it seems that you have modified the button's position. If so, please post the code you modified.

![Image](https://github.com/user-attachments/assets/39e30093-0aee-4a1f-8875-75f4effa1ee0)

**Comment by yiiyahui** [comment]
I'm a bit confused... if the position is incorrect, then the downloads button would also be incorrect. I have been unable to reproduce it, so I can only guess. 

Now there is a download button to its left, keep it. Then switch to vertical layout, remove the 'New Tab' button if it exists, and then switch back to horizontal layout to re-add it

FF has two different 'New Tab' buttons; not sure if that's the reason. You can remove
 `list-style-image: url("neptune/icons/plus.svg") !important;` 
to differentiate between them..

If the issue still exists, try adding a line, `align-self: center;` like this.
```css
#tabs-newtab-button, #new-tab-button {
	list-style-image: url("neptune/icons/plus.svg") !important;

	@media not -moz-pref("sidebar.verticalTabs") {
		&:not(#customization-palette .toolbarbutton-1) {
			position: absolute;
			align-self: center;
			inset-inline-end: calc(var(--tab-min-height) + 2 * var(--toolbar-start-end-padding) + var(--toolbarbutton-outer-padding) - var(--toolbar-start-end-padding) / 2);
		}

		#navigator-toolbox:has(tab[pinned]):has(#tabbrowser-tabs[overflow]) & {
			position: revert;
		}
	}
}
```

**Comment by yiiyahui** [comment]
😂😂😂😂😂😂😂😂😂😂😂
Alright...... now there's a solution. Change it to this, here is the complete code...

```css
#tabs-newtab-button, #new-tab-button {
	list-style-image: url("neptune/icons/plus.svg") !important;

	@media not -moz-pref("sidebar.verticalTabs") {
		&:not(#customization-palette .toolbarbutton-1) {
			position: absolute;
			inset-inline-end: calc(var(--tab-min-height) + 2 * var(--toolbar-start-end-padding) + var(--toolbarbutton-outer-padding) - var(--toolbar-start-end-padding) / 2);
		}

		#navigator-toolbox:not(:has(tab-group)):has(tab:only-of-type) & {
			inset-block:0;
		}

		#navigator-toolbox:has(tab[pinned]):has(#tabbrowser-tabs[overflow]) & {
			position: revert;
		}
	}
}
```

**Comment by yiiyahui** [comment]
No..,I just don’t know what’s going on. Let’s try again..I have already tested it.
```css
#tabs-newtab-button, #new-tab-button {
	list-style-image: url("neptune/icons/plus.svg") !important;

	@media not -moz-pref("sidebar.verticalTabs") {
		&:not(#customization-palette .toolbarbutton-1) {
			position: absolute;
			inset-inline-end: calc(var(--tab-min-height) + 2 * var(--toolbar-start-end-padding) + var(--toolbarbutton-outer-padding) - var(--toolbar-start-end-padding) / 2);
		}

		#tabbrowser-tabs:not(:has(tab-group)):has(tab:only-of-type) & {
			inset-block: 0;
			align-self: center;
		}

		#navigator-toolbox:has(tab[pinned]):has(#tabbrowser-tabs[overflow]) & {
			position: revert;
		}
	}
}
```

Also, are you sure there are no other mods? 

https://github.com/yiiyahui/Neptune-Firefox/blob/58ac81897d86d0d1e8c5c3a99a4abe6b7bee2087/chrome/userChrome.css#L278

and

https://github.com/yiiyahui/Neptune-Firefox/blob/58ac81897d86d0d1e8c5c3a99a4abe6b7bee2087/chrome/userChrome.css#L298
will affect the centering of the button.
