### ISSUE TITLE
New tab and Bookmark! 

### ISSUE THREAD

**Issue by CREATORCorp** [yiiyahui/Neptune-Firefox#9]
Hello! Very nice theme, i always try to find a good safari theme like that. Is there any fix for "NewTab" "+" icon to move after tabs? 
And another question, you know how to make bookmark bar show on hover? i think is the best thing. Thx! Have a good day sir!

**Comment by yiiyahui** [comment]
1: moving only the newtab button will disrupt the existing layout.
2: try copying the following content into userchrome.css.

```css
#PersonalToolbar {
	margin-bottom: -28px;
	transform: rotateX(90deg);
  	transform-origin: top;
	transition: transform .1s linear .3s !important;
	z-index: 1;
}

#navigator-toolbox:hover > #PersonalToolbar {
	transition-delay: .3s;
	transform: rotateX(0);
}
```

**Comment by CREATORCorp** [comment]
It works! Thank you so much!

**Comment by CREATORCorp** [comment]
Last update, hover bookmark don't work.

**Comment by yiiyahui** [comment]
You like it just like I like Messi.

```css
#navigator-toolbox {
	z-index: 3 !important;

	> #PersonalToolbar {
		margin-bottom: -28px;
		transform: rotateX(90deg);
		transform-origin: top;
		transition: .2s linear !important;

		#navigator-toolbox:hover > & {
			transition-delay: .3s !important;
			transform: rotateX(0);
		}
	}
}
```
